ASafeFurrPlace/SafeFurrPlace/config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/index'

  get 'documents/new'

  get 'documents/show'

  resources :documents

  get 'welcome/index'

  get 'welcome/new'

  get 'welcome/create'

  post 'welcome/create'

  delete 'sessions' => 'sessions#destroy'
  match ':controller(/:action(/:id))(.:format)', :via => [:get, :post]
  match "signup", :to => "users#new", :via => [:get, :post]
  match "login", :to => "session#login", :via => [:get, :post]
  match "logout", :to => "session#logout", :via => [:get, :post]
  match "home", :to => "session#home", :via => [:get, :post]
  match "profile", :to => "session#profile", :via => [:get, :post]
  match "setting", :to => "session#setting", :via => [:get, :post]

  root 'welcome#index'

end

ASafeFurrPlace/SafeFurrPlace/app/models/activity.rb
class Activity < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/models/announcement.rb
class Announcement < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
end

ASafeFurrPlace/SafeFurrPlace/app/models/document.rb
class Document < ActiveRecord::Base
	def initialize(params = {})
  file = params.delete(:file)
  super
  if file
    self.filename = sanitize_filename(file.original_filename)
    self.content_type = file.content_type
    self.file_contents = file.read
  end
end
private
  def sanitize_filename(filename)
    # Get only the filename, not the whole path (for IE)
    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
    return File.basename(filename)
  end
end

ASafeFurrPlace/SafeFurrPlace/app/models/registraion.rb
class Registraion < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user

  include PublicActivity::Model
  tracked

  validates :title, presence: true
  validates :body, presence: true
end

ASafeFurrPlace/SafeFurrPlace/app/models/upload.rb
class Upload < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password

  EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true
  #Only on Create so other actions like update password attribute can be nil
  validates_length_of :password, :in => 6..20, :on => :create

  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)    
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end   

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end



  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

ASafeFurrPlace/SafeFurrPlace/app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
	
	  attr_accessor :password

	  before_save :encrypt_password
	  after_save :clear_password

	  EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
	  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	  validates :password, :confirmation => true
	  #Only on Create so other actions like update password attribute can be nil
	  validates_length_of :password, :in => 6..20, :on => :create

	  def self.authenticate(username_or_email="", login_password="")

	    if  EMAIL_REGEX.match(username_or_email)    
	      volunteer = Volunteer.find_by_email(username_or_email)
	    else
	      volunteer = Volunteer.find_by_username(username_or_email)
	    end

	    if volunteer && volunteer.match_password(login_password)
	      return volunteer
	    else
	      return false
	    end
	  end   

	  def match_password(login_password="")
	    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
	  end



	  def encrypt_password
	    unless password.blank?
	      self.salt = BCrypt::Engine.generate_salt
	      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
	    end
	  end

	  def clear_password
	    self.password = nil
	  end

	end

ASafeFurrPlace/SafeFurrPlace/app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/documents_helper.rb
module DocumentsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/items_helper.rb
module ItemsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/photo_helper.rb
module PhotoHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/sessions_helper.rb
module SessionsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/stories_helper.rb
module StoriesHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/upload_helper.rb
module UploadHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/uploads_helper.rb
module UploadsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/user_helper.rb
module UserHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/users_helper.rb
module UsersHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/volunteers_helper.rb
module VolunteersHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ASafeFurrPlace/SafeFurrPlace/app/views/layouts/_footer.html.erb
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                
                <p><%= link_to(image_tag("facebook.png", :class => "img-center"), "https://www.facebook.com/ASafeFurrPlace/timeline") %><br>
                Copyright &copy; A SafeFurr Place 2016</p>
                <%= link_to 'Announcements', controller: 'announcements' %>	
            </div>
        </div>
    </div>
</footer>

ASafeFurrPlace/SafeFurrPlace/app/views/layouts/_header.html.erb
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

    <title>A SafeFurr Place Animal Rescue</title>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag "bootstrap.min" %>

    <!-- Custom CSS -->
    <%= stylesheet_link_tag "SafeFurrPlace" %>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<header>
  
	<%#<div class="brand">A SafeFurr Place</div>
    <div class="address-bar">Animal Rescue</div> %>
    
    <!-- Navigation -->
    
            <!-- Brand and toggle get grouped for better mobile display -->
    <div style="background: white; text-align: center; height: 170px;">
        <!-- The image will go here -->
        <%= image_tag('combine.jpg', :alt => "Image") %>
    </div>            
    
    <div>        
        <ul class="welcome">
                    <li>
                        <%= link_to "Home", root_path %>
                    </li>
                    <li>
                        <%= link_to "About" %>
                    </li>
                    <%# <li>
                        To come....
                        <a href="blog.html">Blog</a>
                    </li> %>
                    <li>
                        <%= link_to "Contact" %>
                    </li>
                    <li>
                        <%= link_to "Login/Volunteer", '/sessions/login'   %>
                    </li>
        </ul>            
    </div>
    
            <!-- /.navbar-collapse -->
        
    
        <!-- /.container -->
    </nav>
</header>

ASafeFurrPlace/SafeFurrPlace/app/views/layouts/_vheader.html.erb
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">

    <title>A SafeFurr Place Animal Rescue</title>

    <!-- Bootstrap Core CSS -->
    <%= stylesheet_link_tag "bootstrap.min" %>

    <!-- Custom CSS -->
    <%= stylesheet_link_tag "SafeFurrPlace" %>

    <!-- Fonts -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Josefin+Slab:100,300,400,600,700,100italic,300italic,400italic,600italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<header>
  
	<%#<div class="brand">A SafeFurr Place</div>
    <div class="address-bar">Animal Rescue</div> %>
    
    <!-- Navigation -->
    
            <!-- Brand and toggle get grouped for better mobile display -->
    <div style="background: white; text-align: center; height: 170px;">
        <!-- The image will go here -->
        <%= image_tag('combine.jpg', :alt => "Image") %>
    </div>            
    
    <div>        
        <ul class="welcome">
                    <li>
                        <%= link_to "Home", sessions_path %>
                    </li>
                    <li>
                        <%= link_to "Animals", documents_path %>
                    </li>
                    <%# <li>
                        To come....
                        <a href="blog.html">Blog</a>
                    </li> %>
                    <li>
                        <%= link_to "Contact" %>
                    </li>
                    <li>
                        <%= link_to 'Logout', '/welcome/', method: :destroy %>
                    </li>
        </ul>            
    </div>
    
            <!-- /.navbar-collapse -->
        
    
        <!-- /.container -->
    </nav>
</header>

ASafeFurrPlace/SafeFurrPlace/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SafeFurrPlace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	
<%= yield %>

</body>
</html>

ASafeFurrPlace/SafeFurrPlace/app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

ASafeFurrPlace/SafeFurrPlace/app/views/shared/_activities.html.erb
<div class="col-sm-3">
  <ul class="list-group">
    <%= render_activities @activities %>
  </ul>
</div>

ASafeFurrPlace/SafeFurrPlace/app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <h3 class="panel-title">The following errors were found while submitting the form:</h3>
    </div>

    <div class="panel-body">
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>