ASafeFurrPlace/SafeFurrPlace/config/routes.rb
Rails.application.routes.draw do
  
  get 'documents/index'

  get 'documents/new'

  get 'documents/show'

  resources :documents

  get 'welcome/index'

  get 'welcome/new'

  get 'welcome/create'

  post 'welcome/create'

  delete 'sessions' => 'sessions#destroy'
  match ':controller(/:action(/:id))(.:format)', :via => [:get, :post]
  match "signup", :to => "users#new", :via => [:get, :post]
  match "login", :to => "session#login", :via => [:get, :post]
  match "logout", :to => "session#logout", :via => [:get, :post]
  match "home", :to => "session#home", :via => [:get, :post]
  match "profile", :to => "session#profile", :via => [:get, :post]
  match "setting", :to => "session#setting", :via => [:get, :post]

  root 'welcome#index'

end

ASafeFurrPlace/SafeFurrPlace/app/models/activity.rb
class Activity < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/models/announcement.rb
class Announcement < ActiveRecord::Base
	validates :title, presence: true,
                    length: { minimum: 5 }
end

ASafeFurrPlace/SafeFurrPlace/app/models/document.rb
class Document < ActiveRecord::Base
	def initialize(params = {})
  file = params.delete(:file)
  super
  if file
    self.filename = sanitize_filename(file.original_filename)
    self.content_type = file.content_type
    self.file_contents = file.read
  end
end
private
  def sanitize_filename(filename)
    # Get only the filename, not the whole path (for IE)
    # Thanks to this article I just found for the tip: http://mattberther.com/2007/10/19/uploading-files-to-a-database-using-rails
    return File.basename(filename)
  end
end

ASafeFurrPlace/SafeFurrPlace/app/models/registraion.rb
class Registraion < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :user

  include PublicActivity::Model
  tracked

  validates :title, presence: true
  validates :body, presence: true
end

ASafeFurrPlace/SafeFurrPlace/app/models/upload.rb
class Upload < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password

  before_save :encrypt_password
  after_save :clear_password

  EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true
  #Only on Create so other actions like update password attribute can be nil
  validates_length_of :password, :in => 6..20, :on => :create

  def self.authenticate(username_or_email="", login_password="")
    if  EMAIL_REGEX.match(username_or_email)    
      user = User.find_by_email(username_or_email)
    else
      user = User.find_by_username(username_or_email)
    end

    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end   

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end



  def encrypt_password
    unless password.blank?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end

  def clear_password
    self.password = nil
  end

end

ASafeFurrPlace/SafeFurrPlace/app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
	
	  attr_accessor :password

	  before_save :encrypt_password
	  after_save :clear_password

	  EMAIL_REGEX = /[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}/i
	  validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	  validates :password, :confirmation => true
	  #Only on Create so other actions like update password attribute can be nil
	  validates_length_of :password, :in => 6..20, :on => :create

	  def self.authenticate(username_or_email="", login_password="")

	    if  EMAIL_REGEX.match(username_or_email)    
	      volunteer = Volunteer.find_by_email(username_or_email)
	    else
	      volunteer = Volunteer.find_by_username(username_or_email)
	    end

	    if volunteer && volunteer.match_password(login_password)
	      return volunteer
	    else
	      return false
	    end
	  end   

	  def match_password(login_password="")
	    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
	  end



	  def encrypt_password
	    unless password.blank?
	      self.salt = BCrypt::Engine.generate_salt
	      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
	    end
	  end

	  def clear_password
	    self.password = nil
	  end

	end

ASafeFurrPlace/SafeFurrPlace/app/models/welcome.rb
class Welcome < ActiveRecord::Base
end

ASafeFurrPlace/SafeFurrPlace/app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: [:show, :edit, :update, :destroy]

  # GET /documents
  # GET /documents.json
  def index
    @documents = Document.all
  end

  def pindex
    @documents = Document.all
  end

  # GET /documents/1
  # GET /documents/1.json
  def show
    @document = Document.find(params[:id])
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # POST /documents
  # POST /documents.json
  def create
    name = params[:document][:file].original_filename
    directory = "app/assets/images/"
    path = File.join(directory, name)
    File.open(path, "wb") { |f| f.write(params[:document][:file].read) }
    flash[:notice] = "File uploaded"

    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: 'Document was successfully created.' }
        format.json { render action: 'show', status: :created, location: @document }
      else
        format.html { render action: 'new' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1
  # PATCH/PUT /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to @document, notice: 'Document was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1
  # DELETE /documents/1.json
  def destroy
    @document.destroy
    respond_to do |format|
      format.html { redirect_to documents_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def document_params
      params.require(:document).permit(:file, :animalname, :animalabout)
    end
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/application_helper.rb
module ApplicationHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/attachments_helper.rb
module AttachmentsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/documents_helper.rb
module DocumentsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/items_helper.rb
module ItemsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/photo_helper.rb
module PhotoHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/sessions_helper.rb
module SessionsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/stories_helper.rb
module StoriesHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/upload_helper.rb
module UploadHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/uploads_helper.rb
module UploadsHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/user_helper.rb
module UserHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/users_helper.rb
module UsersHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/volunteers_helper.rb
module VolunteersHelper
end

ASafeFurrPlace/SafeFurrPlace/app/helpers/welcome_helper.rb
module WelcomeHelper
end

ASafeFurrPlace/SafeFurrPlace/app/views/documents/_form.html.erb
<!-- app/views/documents/_form.html.erb -->
<%= form_for(@document) do |f| %>
	<p>
	  <%= f.label :animalname, "Name" %><br>
	  <%= f.text_field :animalname %>
	</p>
  <p>
    <%= f.label :animalabout, "About" %><br>
    <%= f.text_area :animalabout %>
  </p>
  <div class="field">
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ASafeFurrPlace/SafeFurrPlace/app/views/documents/index.html.erb
<%= render 'layouts/vheader' %>
<div class="container">
<div class="box">

  <%= link_to 'Add Image', documents_new_path %>
  <div class="col-md-12"><br>   
    <div class="well well-lg" style="height: auto;">
        <table>

            <% @documents.each_with_index do |document, i| %>
            <% if i > 0 && i % 4 == 0 %>
            <tr>             
              <td><%= link_to image_tag(document.filename,:size =>"100x100",:alt => "Image"),document_path(document) %></td>
              <td><%= document.animalname %></td>
              <td><%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            </tr><br><br>
            <% else %>
             <td><%= link_to image_tag(document.filename,:size =>"100x100",:alt => "Image"),document_path(document) %></td>
             <td><%= document.animalname %></td>
             <td><%= link_to 'Delete', document, method: :delete, data: { confirm: 'Are you sure?' } %></td>
              <% end %>
            <% end %>

        </table>
    </div>
  </div>
 </div>
</div>

ASafeFurrPlace/SafeFurrPlace/app/views/documents/new.html.erb
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
  <h1>New Image</h1>
   
  <%= render 'form' %>
   
  <%= link_to 'Back', documents_path %>
  </div>
</div>

ASafeFurrPlace/SafeFurrPlace/app/views/documents/pindex.html.erb
<%= render 'layouts/header' %>
<div class="container">
  <div class="row">
    <div class="box">
        <div class="col-lg-12 text-center">
            <div id="carousel-example-generic" class="carousel slide">
                <!-- Indicators -->
                

                <!-- Wrapper for slides -->
                <div class="carousel-inner">
                <% @documents.each_with_index do |document, i| %>
                <% if i == 0 %>
                    <div class="item active">
                         <div class="w3-container w3-center">
                              <h2><%= document.animalname %></h2>
                         </div>
                    <div class="w3-card-12">
                      <%= link_to image_tag(document.filename, :size => "1200x500", :alt => "Picture"), document_path(document) %>
                      
                    </div>
                        
                    </div>
                <% else %>
                    <div class="item">
                         <div class="w3-container w3-center">
                              <h2><%= document.animalname %></h2>
                         </div>
                         <div class="w3-card-12">
                         <%= link_to image_tag(document.filename, :size => "1200x500", :alt => "Picture"), document_path(document) %>
                           
                         </div>
                    </div>
                <% end %>

                <% end %>
                </div>

                <!-- Controls -->
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="icon-prev"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="icon-next"></span>
                </a>
            </div>
            <h2 class="brand-before">
                <small>Click Image to See More</small>
            </h2>
            <h1 class="brand-name">A SafeFurr Place</h1>
            <hr class="tagline-divider">
            <h2>
                <small>
                    <strong>Animal Rescue</strong>
                </small>
            </h2>
            <div style="width: auto; position: relative; float: center;">
             <table>
              <tr>
                <% @documents.each_with_index do |document, i| %>
                  <%= link_to image_tag(document.filename, :size => "100x100", :alt => "Picture"), document_path(document) %>
                <% end %>
              </tr>
             </table>
            </div> 
        </div>
    </div>
  </div>
</div>

ASafeFurrPlace/SafeFurrPlace/app/views/documents/show.html.erb
<h1>Documents#show</h1>
<p>Find me in app/views/documents/show.html.erb</p>